### ISSUE TITLE
Error: logger.addStream is not a function

### ISSUE THREAD

**Issue by Tanuel** [renovatebot/renovate#4095]
**What Renovate type are you using?**
renovate cli, self built from source

**Describe the bug**
Bug possibly introduced in #3671

**Did you see anything helpful in debug logs?**
```
FATAL: Fatal error: logger.addStream is not a function
       "err": {
         "message": "logger.addStream is not a function",
         "stack": "TypeError: logger.addStream is not a function\n    at Object.parseConfigs (/usr/src/tethys-ci-renovate-bot/node_modules/renovate/dist/config/index.js:52:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)"
       }
```

**To Reproduce**
Enable logfile in config.js via the logFile option i guess? When disabling logFile in config everyhing works, but seems to give less output than before the changes (to be verified)

**Expected behavior**
Should work as before
